run on failed

diff --git a/.github/workflows/monitor-sailing-spots.yml b/.github/workflows/monitor-sailing-spots.yml
--- a/.github/workflows/monitor-sailing-spots.yml
+++ b/.github/workflows/monitor-sailing-spots.yml
@@ -74,4 +74,6 @@ jobs:
             git push
           else
             echo "No change -- still $SPOTS spots."
+            echo "Forcing failure to trigger email notification."
+            exit 1
           fi
